2021-10-14 09:57:28,589 - INFO - Started server process [9]
2021-10-14 09:57:28,600 - INFO - Waiting for application startup.
2021-10-14 09:57:28,601 - INFO - Application startup complete.
2021-10-14 11:49:20,302 - INFO - Started server process [8]
2021-10-14 11:49:20,303 - INFO - Waiting for application startup.
2021-10-14 11:49:20,305 - INFO - Application startup complete.
2021-10-14 11:52:06,667 - INFO - Started server process [8]
2021-10-14 11:52:06,668 - INFO - Waiting for application startup.
2021-10-14 11:52:06,671 - INFO - Application startup complete.
2021-10-14 11:54:49,434 - INFO - Started server process [9]
2021-10-14 11:54:49,436 - INFO - Waiting for application startup.
2021-10-14 11:54:49,437 - INFO - Application startup complete.
2021-10-14 11:59:10,573 - INFO - Started server process [9]
2021-10-14 11:59:10,573 - INFO - Waiting for application startup.
2021-10-14 11:59:10,574 - INFO - Application startup complete.
2021-10-14 12:01:10,423 - INFO - Started server process [9]
2021-10-14 12:01:10,424 - INFO - Waiting for application startup.
2021-10-14 12:01:10,425 - INFO - Application startup complete.
2021-10-14 12:09:46,001 - ERROR - Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 396, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/usr/local/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/fastapi/applications.py", line 199, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/applications.py", line 111, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/base.py", line 25, in __call__
    response = await self.dispatch_func(request, self.call_next)
  File "/app/./main.py", line 50, in db_session_middleware
    response = await call_next(request)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/base.py", line 45, in call_next
    task.result()
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/base.py", line 38, in coro
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/cors.py", line 86, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/cors.py", line 142, in simple_response
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/usr/local/lib/python3.9/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 566, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 227, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 41, in app
    response = await func(request)
  File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 201, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 150, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/usr/local/lib/python3.9/site-packages/starlette/concurrency.py", line 34, in run_in_threadpool
    return await loop.run_in_executor(None, func, *args)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/app/./api/resources/v1/account.py", line 70, in create_account
    user_db = user_logic.get_user_by_email(db_session, form_data.email)
  File "/app/./databases/logic/user.py", line 15, in get_user_by_email
    return db_session.query(User) \
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 2762, in first
    return self.limit(1)._iter().first()
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 2846, in _iter
    result = self.session.execute(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1688, in execute
    conn = self._connection_for_bind(bind)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1529, in _connection_for_bind
    return self._transaction._connection_for_bind(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 747, in _connection_for_bind
    conn = bind.connect()
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3194, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3273, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3243, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2097, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3240, in _wrap_pool_connect
    return fn()
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 310, in connect
    return _ConnectionFairy._checkout(self)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 868, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 476, in checkout
    rec = pool._do_get()
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 146, in _do_get
    self._dec_overflow()
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
    return self._create_connection()
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 256, in _create_connection
    return _ConnectionRecord(self)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 371, in __init__
    self.__connect()
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 666, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 661, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/create.py", line 590, in connect
    return dialect.connect(*cargs, **cparams)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 584, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/usr/local/lib/python3.9/site-packages/psycopg2/__init__.py", line 127, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not connect to server: Connection refused
	Is the server running on host "localhost" (127.0.0.1) and accepting
	TCP/IP connections on port 5432?
could not connect to server: Cannot assign requested address
	Is the server running on host "localhost" (::1) and accepting
	TCP/IP connections on port 5432?

(Background on this error at: https://sqlalche.me/e/14/e3q8)
2021-10-14 12:10:34,195 - INFO - Started server process [9]
2021-10-14 12:10:34,196 - INFO - Waiting for application startup.
2021-10-14 12:10:34,198 - INFO - Application startup complete.
2021-10-14 12:10:38,019 - INFO - select pg_catalog.version()
2021-10-14 12:10:38,020 - INFO - [raw sql] {}
2021-10-14 12:10:38,023 - INFO - select current_schema()
2021-10-14 12:10:38,025 - INFO - [raw sql] {}
2021-10-14 12:10:38,027 - INFO - show standard_conforming_strings
2021-10-14 12:10:38,028 - INFO - [raw sql] {}
2021-10-14 12:10:38,031 - INFO - BEGIN (implicit)
2021-10-14 12:10:38,037 - INFO - SELECT reactchess."user".id AS reactchess_user_id, reactchess."user".first_name AS reactchess_user_first_name, reactchess."user".last_name AS reactchess_user_last_name, reactchess."user".email AS reactchess_user_email, reactchess."user".phone AS reactchess_user_phone, reactchess."user".password AS reactchess_user_password, reactchess."user".create_date AS reactchess_user_create_date, reactchess."user".update_date AS reactchess_user_update_date 
FROM reactchess."user" 
WHERE reactchess."user".email = %(email_1)s 
 LIMIT %(param_1)s
2021-10-14 12:10:38,038 - INFO - [generated in 0.00167s] {'email_1': 'duynguyenngoc@hotmail.com', 'param_1': 1}
2021-10-14 12:10:38,056 - ERROR - Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 396, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/usr/local/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/fastapi/applications.py", line 199, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/applications.py", line 111, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/base.py", line 25, in __call__
    response = await self.dispatch_func(request, self.call_next)
  File "/app/./main.py", line 50, in db_session_middleware
    response = await call_next(request)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/base.py", line 45, in call_next
    task.result()
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/base.py", line 38, in coro
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/cors.py", line 86, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/cors.py", line 142, in simple_response
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/usr/local/lib/python3.9/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 566, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 227, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 41, in app
    response = await func(request)
  File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 201, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 150, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/usr/local/lib/python3.9/site-packages/starlette/concurrency.py", line 34, in run_in_threadpool
    return await loop.run_in_executor(None, func, *args)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/app/./api/resources/v1/account.py", line 74, in create_account
    user.password = password_helper.get_password_hash(user.password)
  File "/app/./securities/password.py", line 11, in get_password_hash
    return pwd_context.hash(password)
  File "/usr/local/lib/python3.9/site-packages/passlib/context.py", line 2258, in hash
    return record.hash(secret, **kwds)
  File "/usr/local/lib/python3.9/site-packages/passlib/utils/handlers.py", line 779, in hash
    self.checksum = self._calc_checksum(secret)
  File "/usr/local/lib/python3.9/site-packages/passlib/handlers/bcrypt.py", line 591, in _calc_checksum
    self._stub_requires_backend()
  File "/usr/local/lib/python3.9/site-packages/passlib/utils/handlers.py", line 2254, in _stub_requires_backend
    cls.set_backend()
  File "/usr/local/lib/python3.9/site-packages/passlib/utils/handlers.py", line 2156, in set_backend
    return owner.set_backend(name, dryrun=dryrun)
  File "/usr/local/lib/python3.9/site-packages/passlib/utils/handlers.py", line 2176, in set_backend
    raise default_error
passlib.exc.MissingBackendError: bcrypt: no backends available -- recommend you install one (e.g. 'pip install bcrypt')
2021-10-14 12:13:31,685 - INFO - Started server process [9]
2021-10-14 12:13:31,686 - INFO - Waiting for application startup.
2021-10-14 12:13:31,688 - INFO - Application startup complete.
2021-10-14 12:14:04,481 - INFO - select pg_catalog.version()
2021-10-14 12:14:04,482 - INFO - [raw sql] {}
2021-10-14 12:14:04,485 - INFO - select current_schema()
2021-10-14 12:14:04,485 - INFO - [raw sql] {}
2021-10-14 12:14:04,487 - INFO - show standard_conforming_strings
2021-10-14 12:14:04,487 - INFO - [raw sql] {}
2021-10-14 12:14:04,489 - INFO - BEGIN (implicit)
2021-10-14 12:14:04,496 - INFO - SELECT reactchess."user".id AS reactchess_user_id, reactchess."user".first_name AS reactchess_user_first_name, reactchess."user".last_name AS reactchess_user_last_name, reactchess."user".email AS reactchess_user_email, reactchess."user".phone AS reactchess_user_phone, reactchess."user".password AS reactchess_user_password, reactchess."user".create_date AS reactchess_user_create_date, reactchess."user".update_date AS reactchess_user_update_date 
FROM reactchess."user" 
WHERE reactchess."user".email = %(email_1)s 
 LIMIT %(param_1)s
2021-10-14 12:14:04,497 - INFO - [generated in 0.00121s] {'email_1': 'duynguyenngoc@hotmail.com', 'param_1': 1}
2021-10-14 12:14:04,815 - INFO - INSERT INTO reactchess."user" (first_name, last_name, email, phone, password, create_date, update_date) VALUES (%(first_name)s, %(last_name)s, %(email)s, %(phone)s, %(password)s, %(create_date)s, %(update_date)s) RETURNING reactchess."user".id
2021-10-14 12:14:04,817 - INFO - [generated in 0.00199s] {'first_name': 'Duy', 'last_name': 'Nguyen', 'email': 'duynguyenngoc@hotmail.com', 'phone': '+84399360638', 'password': '$2b$12$tsKIuBE3W4prdURvAjQMSuMvV0agaUBm/58TBJbQKFTRf.OECp9gO', 'create_date': datetime.datetime(2021, 10, 14, 12, 13, 30, 863637, tzinfo=<UTC>), 'update_date': None}
2021-10-14 12:14:04,821 - INFO - COMMIT
2021-10-14 12:14:04,829 - INFO - BEGIN (implicit)
2021-10-14 12:14:04,831 - INFO - SELECT reactchess."user".id, reactchess."user".first_name, reactchess."user".last_name, reactchess."user".email, reactchess."user".phone, reactchess."user".password, reactchess."user".create_date, reactchess."user".update_date 
FROM reactchess."user" 
WHERE reactchess."user".id = %(pk_1)s
2021-10-14 12:14:04,832 - INFO - [generated in 0.00102s] {'pk_1': 1}
2021-10-14 12:14:04,836 - INFO - ROLLBACK
2021-10-14 14:13:33,835 - INFO - BEGIN (implicit)
2021-10-14 14:13:33,850 - INFO - SELECT reactchess."user".id AS reactchess_user_id, reactchess."user".first_name AS reactchess_user_first_name, reactchess."user".last_name AS reactchess_user_last_name, reactchess."user".email AS reactchess_user_email, reactchess."user".phone AS reactchess_user_phone, reactchess."user".password AS reactchess_user_password, reactchess."user".create_date AS reactchess_user_create_date, reactchess."user".update_date AS reactchess_user_update_date 
FROM reactchess."user" 
WHERE reactchess."user".email = %(email_1)s 
 LIMIT %(param_1)s
2021-10-14 14:13:33,858 - INFO - [cached since 7169s ago] {'email_1': 'duynguyenngoc@hotmail.com', 'param_1': 1}
2021-10-14 14:13:34,302 - ERROR - Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 396, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/usr/local/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/fastapi/applications.py", line 199, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/applications.py", line 111, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/base.py", line 25, in __call__
    response = await self.dispatch_func(request, self.call_next)
  File "/app/./main.py", line 50, in db_session_middleware
    response = await call_next(request)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/base.py", line 45, in call_next
    task.result()
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/base.py", line 38, in coro
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/cors.py", line 86, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/cors.py", line 142, in simple_response
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/usr/local/lib/python3.9/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 566, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 227, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 41, in app
    response = await func(request)
  File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 201, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 150, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/usr/local/lib/python3.9/site-packages/starlette/concurrency.py", line 34, in run_in_threadpool
    return await loop.run_in_executor(None, func, *args)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/app/./api/resources/v1/account.py", line 31, in login
    token,  = account_entity.Token(
ValueError: too many values to unpack (expected 1)
2021-10-14 14:14:15,010 - INFO - BEGIN (implicit)
2021-10-14 14:14:15,011 - INFO - SELECT reactchess."user".id AS reactchess_user_id, reactchess."user".first_name AS reactchess_user_first_name, reactchess."user".last_name AS reactchess_user_last_name, reactchess."user".email AS reactchess_user_email, reactchess."user".phone AS reactchess_user_phone, reactchess."user".password AS reactchess_user_password, reactchess."user".create_date AS reactchess_user_create_date, reactchess."user".update_date AS reactchess_user_update_date 
FROM reactchess."user" 
WHERE reactchess."user".email = %(email_1)s 
 LIMIT %(param_1)s
2021-10-14 14:14:15,012 - INFO - [cached since 7211s ago] {'email_1': 'duynguyenngoc@hotmail.com', 'param_1': 1}
2021-10-14 14:14:15,323 - ERROR - Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 396, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/usr/local/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/fastapi/applications.py", line 199, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/applications.py", line 111, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/base.py", line 25, in __call__
    response = await self.dispatch_func(request, self.call_next)
  File "/app/./main.py", line 50, in db_session_middleware
    response = await call_next(request)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/base.py", line 45, in call_next
    task.result()
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/base.py", line 38, in coro
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/cors.py", line 86, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/cors.py", line 142, in simple_response
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/usr/local/lib/python3.9/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 566, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 227, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 41, in app
    response = await func(request)
  File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 201, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 150, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/usr/local/lib/python3.9/site-packages/starlette/concurrency.py", line 34, in run_in_threadpool
    return await loop.run_in_executor(None, func, *args)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/app/./api/resources/v1/account.py", line 31, in login
    token,  = account_entity.Token(
ValueError: too many values to unpack (expected 1)
2021-10-14 14:14:55,970 - INFO - BEGIN (implicit)
2021-10-14 14:14:55,971 - INFO - SELECT reactchess."user".id AS reactchess_user_id, reactchess."user".first_name AS reactchess_user_first_name, reactchess."user".last_name AS reactchess_user_last_name, reactchess."user".email AS reactchess_user_email, reactchess."user".phone AS reactchess_user_phone, reactchess."user".password AS reactchess_user_password, reactchess."user".create_date AS reactchess_user_create_date, reactchess."user".update_date AS reactchess_user_update_date 
FROM reactchess."user" 
WHERE reactchess."user".email = %(email_1)s 
 LIMIT %(param_1)s
2021-10-14 14:14:55,972 - INFO - [cached since 7251s ago] {'email_1': 'duynguyenngoc@hotmail.com', 'param_1': 1}
2021-10-14 14:14:56,272 - ERROR - Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 396, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/usr/local/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/fastapi/applications.py", line 199, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/applications.py", line 111, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/base.py", line 25, in __call__
    response = await self.dispatch_func(request, self.call_next)
  File "/app/./main.py", line 50, in db_session_middleware
    response = await call_next(request)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/base.py", line 45, in call_next
    task.result()
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/base.py", line 38, in coro
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/cors.py", line 86, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/cors.py", line 142, in simple_response
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/usr/local/lib/python3.9/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 566, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 227, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 41, in app
    response = await func(request)
  File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 201, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 150, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/usr/local/lib/python3.9/site-packages/starlette/concurrency.py", line 34, in run_in_threadpool
    return await loop.run_in_executor(None, func, *args)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/app/./api/resources/v1/account.py", line 31, in login
    token,  = account_entity.Token(
ValueError: too many values to unpack (expected 1)
2021-10-14 14:15:11,346 - INFO - BEGIN (implicit)
2021-10-14 14:15:11,347 - INFO - SELECT reactchess."user".id AS reactchess_user_id, reactchess."user".first_name AS reactchess_user_first_name, reactchess."user".last_name AS reactchess_user_last_name, reactchess."user".email AS reactchess_user_email, reactchess."user".phone AS reactchess_user_phone, reactchess."user".password AS reactchess_user_password, reactchess."user".create_date AS reactchess_user_create_date, reactchess."user".update_date AS reactchess_user_update_date 
FROM reactchess."user" 
WHERE reactchess."user".email = %(email_1)s 
 LIMIT %(param_1)s
2021-10-14 14:15:11,347 - INFO - [cached since 7267s ago] {'email_1': 'duynguyenngoc@hotmail.com', 'param_1': 1}
2021-10-14 14:15:11,621 - ERROR - Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 396, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/usr/local/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/fastapi/applications.py", line 199, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/applications.py", line 111, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/base.py", line 25, in __call__
    response = await self.dispatch_func(request, self.call_next)
  File "/app/./main.py", line 50, in db_session_middleware
    response = await call_next(request)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/base.py", line 45, in call_next
    task.result()
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/base.py", line 38, in coro
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/cors.py", line 86, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/cors.py", line 142, in simple_response
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/usr/local/lib/python3.9/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 566, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 227, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 41, in app
    response = await func(request)
  File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 201, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 150, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/usr/local/lib/python3.9/site-packages/starlette/concurrency.py", line 34, in run_in_threadpool
    return await loop.run_in_executor(None, func, *args)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/app/./api/resources/v1/account.py", line 31, in login
    token,  = account_entity.Token(
ValueError: too many values to unpack (expected 1)
2021-10-14 14:15:45,705 - INFO - BEGIN (implicit)
2021-10-14 14:15:45,706 - INFO - SELECT reactchess."user".id AS reactchess_user_id, reactchess."user".first_name AS reactchess_user_first_name, reactchess."user".last_name AS reactchess_user_last_name, reactchess."user".email AS reactchess_user_email, reactchess."user".phone AS reactchess_user_phone, reactchess."user".password AS reactchess_user_password, reactchess."user".create_date AS reactchess_user_create_date, reactchess."user".update_date AS reactchess_user_update_date 
FROM reactchess."user" 
WHERE reactchess."user".email = %(email_1)s 
 LIMIT %(param_1)s
2021-10-14 14:15:45,707 - INFO - [cached since 7301s ago] {'email_1': 'duynguyenngoc@hotmail.com', 'param_1': 1}
2021-10-14 14:15:45,994 - ERROR - Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 396, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/usr/local/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/fastapi/applications.py", line 199, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/applications.py", line 111, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/base.py", line 25, in __call__
    response = await self.dispatch_func(request, self.call_next)
  File "/app/./main.py", line 50, in db_session_middleware
    response = await call_next(request)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/base.py", line 45, in call_next
    task.result()
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/base.py", line 38, in coro
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/cors.py", line 86, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/cors.py", line 142, in simple_response
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/usr/local/lib/python3.9/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 566, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 227, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 41, in app
    response = await func(request)
  File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 201, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 150, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/usr/local/lib/python3.9/site-packages/starlette/concurrency.py", line 34, in run_in_threadpool
    return await loop.run_in_executor(None, func, *args)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/app/./api/resources/v1/account.py", line 31, in login
    token,  = account_entity.Token(
ValueError: too many values to unpack (expected 1)
2021-10-14 14:16:47,938 - INFO - BEGIN (implicit)
2021-10-14 14:16:47,938 - INFO - SELECT reactchess."user".id AS reactchess_user_id, reactchess."user".first_name AS reactchess_user_first_name, reactchess."user".last_name AS reactchess_user_last_name, reactchess."user".email AS reactchess_user_email, reactchess."user".phone AS reactchess_user_phone, reactchess."user".password AS reactchess_user_password, reactchess."user".create_date AS reactchess_user_create_date, reactchess."user".update_date AS reactchess_user_update_date 
FROM reactchess."user" 
WHERE reactchess."user".email = %(email_1)s 
 LIMIT %(param_1)s
2021-10-14 14:16:47,939 - INFO - [cached since 7363s ago] {'email_1': 'duynguyenngoc@hotmail.com', 'param_1': 1}
2021-10-14 14:16:48,257 - ERROR - Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 396, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/usr/local/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/fastapi/applications.py", line 199, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/applications.py", line 111, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/base.py", line 25, in __call__
    response = await self.dispatch_func(request, self.call_next)
  File "/app/./main.py", line 50, in db_session_middleware
    response = await call_next(request)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/base.py", line 45, in call_next
    task.result()
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/base.py", line 38, in coro
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/cors.py", line 86, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/cors.py", line 142, in simple_response
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/usr/local/lib/python3.9/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 566, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 227, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 41, in app
    response = await func(request)
  File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 201, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 150, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/usr/local/lib/python3.9/site-packages/starlette/concurrency.py", line 34, in run_in_threadpool
    return await loop.run_in_executor(None, func, *args)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/app/./api/resources/v1/account.py", line 31, in login
    token,  = account_entity.Token(
ValueError: too many values to unpack (expected 1)
2021-10-14 14:17:27,545 - INFO - BEGIN (implicit)
2021-10-14 14:17:27,546 - INFO - SELECT reactchess."user".id AS reactchess_user_id, reactchess."user".first_name AS reactchess_user_first_name, reactchess."user".last_name AS reactchess_user_last_name, reactchess."user".email AS reactchess_user_email, reactchess."user".phone AS reactchess_user_phone, reactchess."user".password AS reactchess_user_password, reactchess."user".create_date AS reactchess_user_create_date, reactchess."user".update_date AS reactchess_user_update_date 
FROM reactchess."user" 
WHERE reactchess."user".email = %(email_1)s 
 LIMIT %(param_1)s
2021-10-14 14:17:27,550 - INFO - [cached since 7403s ago] {'email_1': 'duynguyenngoc@hotmail.com', 'param_1': 1}
2021-10-14 14:17:27,954 - ERROR - Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 396, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/usr/local/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/fastapi/applications.py", line 199, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/applications.py", line 111, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/base.py", line 25, in __call__
    response = await self.dispatch_func(request, self.call_next)
  File "/app/./main.py", line 50, in db_session_middleware
    response = await call_next(request)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/base.py", line 45, in call_next
    task.result()
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/base.py", line 38, in coro
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/cors.py", line 86, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/cors.py", line 142, in simple_response
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/usr/local/lib/python3.9/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 566, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 227, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 41, in app
    response = await func(request)
  File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 201, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 150, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/usr/local/lib/python3.9/site-packages/starlette/concurrency.py", line 34, in run_in_threadpool
    return await loop.run_in_executor(None, func, *args)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/app/./api/resources/v1/account.py", line 31, in login
    token,  = account_entity.Token(
ValueError: too many values to unpack (expected 1)
2021-10-14 14:17:33,349 - INFO - BEGIN (implicit)
2021-10-14 14:17:33,350 - INFO - SELECT reactchess."user".id AS reactchess_user_id, reactchess."user".first_name AS reactchess_user_first_name, reactchess."user".last_name AS reactchess_user_last_name, reactchess."user".email AS reactchess_user_email, reactchess."user".phone AS reactchess_user_phone, reactchess."user".password AS reactchess_user_password, reactchess."user".create_date AS reactchess_user_create_date, reactchess."user".update_date AS reactchess_user_update_date 
FROM reactchess."user" 
WHERE reactchess."user".email = %(email_1)s 
 LIMIT %(param_1)s
2021-10-14 14:17:33,351 - INFO - [cached since 7409s ago] {'email_1': 'duynguyenngoc@hotmail.com', 'param_1': 1}
2021-10-14 14:17:33,654 - ERROR - Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 396, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/usr/local/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/fastapi/applications.py", line 199, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/applications.py", line 111, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/base.py", line 25, in __call__
    response = await self.dispatch_func(request, self.call_next)
  File "/app/./main.py", line 50, in db_session_middleware
    response = await call_next(request)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/base.py", line 45, in call_next
    task.result()
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/base.py", line 38, in coro
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/cors.py", line 86, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/cors.py", line 142, in simple_response
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/usr/local/lib/python3.9/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 566, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 227, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 41, in app
    response = await func(request)
  File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 201, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 150, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/usr/local/lib/python3.9/site-packages/starlette/concurrency.py", line 34, in run_in_threadpool
    return await loop.run_in_executor(None, func, *args)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/app/./api/resources/v1/account.py", line 31, in login
    token,  = account_entity.Token(
ValueError: too many values to unpack (expected 1)
2021-10-14 14:17:39,926 - INFO - BEGIN (implicit)
2021-10-14 14:17:39,927 - INFO - SELECT reactchess."user".id AS reactchess_user_id, reactchess."user".first_name AS reactchess_user_first_name, reactchess."user".last_name AS reactchess_user_last_name, reactchess."user".email AS reactchess_user_email, reactchess."user".phone AS reactchess_user_phone, reactchess."user".password AS reactchess_user_password, reactchess."user".create_date AS reactchess_user_create_date, reactchess."user".update_date AS reactchess_user_update_date 
FROM reactchess."user" 
WHERE reactchess."user".email = %(email_1)s 
 LIMIT %(param_1)s
2021-10-14 14:17:39,927 - INFO - [cached since 7415s ago] {'email_1': 'duynguyenngoc@hotmail.com', 'param_1': 1}
2021-10-14 14:17:40,197 - ERROR - Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 396, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/usr/local/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/fastapi/applications.py", line 199, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/applications.py", line 111, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/base.py", line 25, in __call__
    response = await self.dispatch_func(request, self.call_next)
  File "/app/./main.py", line 50, in db_session_middleware
    response = await call_next(request)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/base.py", line 45, in call_next
    task.result()
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/base.py", line 38, in coro
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/cors.py", line 86, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/cors.py", line 142, in simple_response
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/usr/local/lib/python3.9/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 566, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 227, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 41, in app
    response = await func(request)
  File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 201, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 150, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/usr/local/lib/python3.9/site-packages/starlette/concurrency.py", line 34, in run_in_threadpool
    return await loop.run_in_executor(None, func, *args)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/app/./api/resources/v1/account.py", line 31, in login
    token,  = account_entity.Token(
ValueError: too many values to unpack (expected 1)
2021-10-14 14:17:43,978 - INFO - BEGIN (implicit)
2021-10-14 14:17:43,980 - INFO - SELECT reactchess."user".id AS reactchess_user_id, reactchess."user".first_name AS reactchess_user_first_name, reactchess."user".last_name AS reactchess_user_last_name, reactchess."user".email AS reactchess_user_email, reactchess."user".phone AS reactchess_user_phone, reactchess."user".password AS reactchess_user_password, reactchess."user".create_date AS reactchess_user_create_date, reactchess."user".update_date AS reactchess_user_update_date 
FROM reactchess."user" 
WHERE reactchess."user".email = %(email_1)s 
 LIMIT %(param_1)s
2021-10-14 14:17:43,981 - INFO - [cached since 7419s ago] {'email_1': 'duynguyenngoc@hotmail.com', 'param_1': 1}
2021-10-14 14:17:44,266 - ERROR - Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 396, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/usr/local/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/fastapi/applications.py", line 199, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/applications.py", line 111, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/base.py", line 25, in __call__
    response = await self.dispatch_func(request, self.call_next)
  File "/app/./main.py", line 50, in db_session_middleware
    response = await call_next(request)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/base.py", line 45, in call_next
    task.result()
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/base.py", line 38, in coro
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/cors.py", line 86, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/cors.py", line 142, in simple_response
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/usr/local/lib/python3.9/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 566, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 227, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 41, in app
    response = await func(request)
  File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 201, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 150, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/usr/local/lib/python3.9/site-packages/starlette/concurrency.py", line 34, in run_in_threadpool
    return await loop.run_in_executor(None, func, *args)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/app/./api/resources/v1/account.py", line 31, in login
    token,  = account_entity.Token(
ValueError: too many values to unpack (expected 1)
2021-10-14 14:17:53,875 - INFO - BEGIN (implicit)
2021-10-14 14:17:53,876 - INFO - SELECT reactchess."user".id AS reactchess_user_id, reactchess."user".first_name AS reactchess_user_first_name, reactchess."user".last_name AS reactchess_user_last_name, reactchess."user".email AS reactchess_user_email, reactchess."user".phone AS reactchess_user_phone, reactchess."user".password AS reactchess_user_password, reactchess."user".create_date AS reactchess_user_create_date, reactchess."user".update_date AS reactchess_user_update_date 
FROM reactchess."user" 
WHERE reactchess."user".email = %(email_1)s 
 LIMIT %(param_1)s
2021-10-14 14:17:53,877 - INFO - [cached since 7429s ago] {'email_1': 'duynguyenngoc@hotmail.com', 'param_1': 1}
2021-10-14 14:17:54,168 - ERROR - Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 396, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/usr/local/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/fastapi/applications.py", line 199, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/applications.py", line 111, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/base.py", line 25, in __call__
    response = await self.dispatch_func(request, self.call_next)
  File "/app/./main.py", line 50, in db_session_middleware
    response = await call_next(request)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/base.py", line 45, in call_next
    task.result()
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/base.py", line 38, in coro
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/cors.py", line 86, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/cors.py", line 142, in simple_response
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/usr/local/lib/python3.9/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 566, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 227, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 41, in app
    response = await func(request)
  File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 201, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 150, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/usr/local/lib/python3.9/site-packages/starlette/concurrency.py", line 34, in run_in_threadpool
    return await loop.run_in_executor(None, func, *args)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/app/./api/resources/v1/account.py", line 31, in login
    token,  = account_entity.Token(
ValueError: too many values to unpack (expected 1)
2021-10-14 14:18:25,290 - INFO - BEGIN (implicit)
2021-10-14 14:18:25,291 - INFO - SELECT reactchess."user".id AS reactchess_user_id, reactchess."user".first_name AS reactchess_user_first_name, reactchess."user".last_name AS reactchess_user_last_name, reactchess."user".email AS reactchess_user_email, reactchess."user".phone AS reactchess_user_phone, reactchess."user".password AS reactchess_user_password, reactchess."user".create_date AS reactchess_user_create_date, reactchess."user".update_date AS reactchess_user_update_date 
FROM reactchess."user" 
WHERE reactchess."user".email = %(email_1)s 
 LIMIT %(param_1)s
2021-10-14 14:18:25,292 - INFO - [cached since 7461s ago] {'email_1': 'duynguyenngoc@hotmail.com', 'param_1': 1}
2021-10-14 14:18:25,583 - ERROR - Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 396, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/usr/local/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/fastapi/applications.py", line 199, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/applications.py", line 111, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/base.py", line 25, in __call__
    response = await self.dispatch_func(request, self.call_next)
  File "/app/./main.py", line 50, in db_session_middleware
    response = await call_next(request)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/base.py", line 45, in call_next
    task.result()
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/base.py", line 38, in coro
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/cors.py", line 86, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/cors.py", line 142, in simple_response
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/usr/local/lib/python3.9/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 566, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 227, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 41, in app
    response = await func(request)
  File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 201, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 150, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/usr/local/lib/python3.9/site-packages/starlette/concurrency.py", line 34, in run_in_threadpool
    return await loop.run_in_executor(None, func, *args)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/app/./api/resources/v1/account.py", line 31, in login
    token,  = account_entity.Token(
ValueError: too many values to unpack (expected 1)
2021-10-14 14:18:35,571 - INFO - Shutting down
2021-10-14 14:18:35,673 - INFO - Waiting for application shutdown.
2021-10-14 14:18:35,675 - INFO - Application shutdown complete.
2021-10-14 14:18:35,677 - INFO - Finished server process [9]
2021-10-14 14:18:40,289 - INFO - Started server process [112]
2021-10-14 14:18:40,292 - INFO - Waiting for application startup.
2021-10-14 14:18:40,294 - INFO - Application startup complete.
2021-10-14 14:19:08,714 - INFO - Shutting down
2021-10-14 14:19:08,816 - INFO - Waiting for application shutdown.
2021-10-14 14:19:08,817 - INFO - Application shutdown complete.
2021-10-14 14:19:08,818 - INFO - Finished server process [112]
2021-10-14 14:19:11,457 - INFO - Started server process [214]
2021-10-14 14:19:11,458 - INFO - Waiting for application startup.
2021-10-14 14:19:11,458 - INFO - Application startup complete.
2021-10-14 14:19:11,487 - INFO - select pg_catalog.version()
2021-10-14 14:19:11,488 - INFO - [raw sql] {}
2021-10-14 14:19:11,491 - INFO - select current_schema()
2021-10-14 14:19:11,491 - INFO - [raw sql] {}
2021-10-14 14:19:11,494 - INFO - show standard_conforming_strings
2021-10-14 14:19:11,494 - INFO - [raw sql] {}
2021-10-14 14:19:11,496 - INFO - BEGIN (implicit)
2021-10-14 14:19:11,501 - INFO - SELECT reactchess."user".id AS reactchess_user_id, reactchess."user".first_name AS reactchess_user_first_name, reactchess."user".last_name AS reactchess_user_last_name, reactchess."user".email AS reactchess_user_email, reactchess."user".phone AS reactchess_user_phone, reactchess."user".password AS reactchess_user_password, reactchess."user".create_date AS reactchess_user_create_date, reactchess."user".update_date AS reactchess_user_update_date 
FROM reactchess."user" 
WHERE reactchess."user".email = %(email_1)s 
 LIMIT %(param_1)s
2021-10-14 14:19:11,501 - INFO - [generated in 0.00078s] {'email_1': 'duynguyenngoc@hotmail.com', 'param_1': 1}
2021-10-14 14:19:11,797 - INFO - ROLLBACK
2021-10-14 14:19:57,754 - INFO - BEGIN (implicit)
2021-10-14 14:19:57,755 - INFO - SELECT reactchess."user".id AS reactchess_user_id, reactchess."user".first_name AS reactchess_user_first_name, reactchess."user".last_name AS reactchess_user_last_name, reactchess."user".email AS reactchess_user_email, reactchess."user".phone AS reactchess_user_phone, reactchess."user".password AS reactchess_user_password, reactchess."user".create_date AS reactchess_user_create_date, reactchess."user".update_date AS reactchess_user_update_date 
FROM reactchess."user" 
WHERE reactchess."user".email = %(email_1)s 
 LIMIT %(param_1)s
2021-10-14 14:19:57,756 - INFO - [cached since 46.26s ago] {'email_1': 'duynguyenngoc@hotmail.com', 'param_1': 1}
2021-10-14 14:19:58,056 - INFO - ROLLBACK
2021-10-14 14:24:15,972 - INFO - BEGIN (implicit)
2021-10-14 14:24:15,973 - INFO - SELECT reactchess."user".id AS reactchess_user_id, reactchess."user".first_name AS reactchess_user_first_name, reactchess."user".last_name AS reactchess_user_last_name, reactchess."user".email AS reactchess_user_email, reactchess."user".phone AS reactchess_user_phone, reactchess."user".password AS reactchess_user_password, reactchess."user".create_date AS reactchess_user_create_date, reactchess."user".update_date AS reactchess_user_update_date 
FROM reactchess."user" 
WHERE reactchess."user".email = %(email_1)s 
 LIMIT %(param_1)s
2021-10-14 14:24:15,973 - INFO - [cached since 304.5s ago] {'email_1': 'duynguyenngoc@hotmail.com', 'param_1': 1}
2021-10-14 14:24:16,259 - INFO - ROLLBACK
2021-10-14 14:25:24,195 - INFO - BEGIN (implicit)
2021-10-14 14:25:24,197 - INFO - SELECT reactchess."user".id AS reactchess_user_id, reactchess."user".first_name AS reactchess_user_first_name, reactchess."user".last_name AS reactchess_user_last_name, reactchess."user".email AS reactchess_user_email, reactchess."user".phone AS reactchess_user_phone, reactchess."user".password AS reactchess_user_password, reactchess."user".create_date AS reactchess_user_create_date, reactchess."user".update_date AS reactchess_user_update_date 
FROM reactchess."user" 
WHERE reactchess."user".email = %(email_1)s 
 LIMIT %(param_1)s
2021-10-14 14:25:24,198 - INFO - [cached since 372.7s ago] {'email_1': 'duynguyenngoc@hotmail.com', 'param_1': 1}
2021-10-14 14:25:24,462 - INFO - ROLLBACK
2021-10-14 14:26:51,697 - INFO - BEGIN (implicit)
2021-10-14 14:26:51,698 - INFO - SELECT reactchess."user".id AS reactchess_user_id, reactchess."user".first_name AS reactchess_user_first_name, reactchess."user".last_name AS reactchess_user_last_name, reactchess."user".email AS reactchess_user_email, reactchess."user".phone AS reactchess_user_phone, reactchess."user".password AS reactchess_user_password, reactchess."user".create_date AS reactchess_user_create_date, reactchess."user".update_date AS reactchess_user_update_date 
FROM reactchess."user" 
WHERE reactchess."user".email = %(email_1)s 
 LIMIT %(param_1)s
2021-10-14 14:26:51,700 - INFO - [cached since 460.2s ago] {'email_1': 'duynguyenngoc@hotmail.com', 'param_1': 1}
2021-10-14 14:26:51,988 - INFO - ROLLBACK
2021-10-14 14:27:23,439 - INFO - Shutting down
2021-10-14 14:27:23,540 - INFO - Waiting for application shutdown.
2021-10-14 14:27:23,541 - INFO - Application shutdown complete.
2021-10-14 14:27:23,542 - INFO - Finished server process [214]
2021-10-14 14:27:26,373 - INFO - Started server process [317]
2021-10-14 14:27:26,374 - INFO - Waiting for application startup.
2021-10-14 14:27:26,375 - INFO - Application startup complete.
2021-10-14 14:27:38,564 - INFO - select pg_catalog.version()
2021-10-14 14:27:38,566 - INFO - [raw sql] {}
2021-10-14 14:27:38,571 - INFO - select current_schema()
2021-10-14 14:27:38,573 - INFO - [raw sql] {}
2021-10-14 14:27:38,575 - INFO - show standard_conforming_strings
2021-10-14 14:27:38,576 - INFO - [raw sql] {}
2021-10-14 14:27:38,578 - INFO - BEGIN (implicit)
2021-10-14 14:27:38,583 - INFO - SELECT reactchess."user".id AS reactchess_user_id, reactchess."user".first_name AS reactchess_user_first_name, reactchess."user".last_name AS reactchess_user_last_name, reactchess."user".email AS reactchess_user_email, reactchess."user".phone AS reactchess_user_phone, reactchess."user".password AS reactchess_user_password, reactchess."user".create_date AS reactchess_user_create_date, reactchess."user".update_date AS reactchess_user_update_date 
FROM reactchess."user" 
WHERE reactchess."user".email = %(email_1)s 
 LIMIT %(param_1)s
2021-10-14 14:27:38,584 - INFO - [generated in 0.00084s] {'email_1': 'duynguyenngoc@hotmail.com', 'param_1': 1}
2021-10-14 14:27:38,883 - INFO - ROLLBACK
2021-10-14 14:28:12,088 - INFO - BEGIN (implicit)
2021-10-14 14:28:12,090 - INFO - SELECT reactchess."user".id AS reactchess_user_id, reactchess."user".first_name AS reactchess_user_first_name, reactchess."user".last_name AS reactchess_user_last_name, reactchess."user".email AS reactchess_user_email, reactchess."user".phone AS reactchess_user_phone, reactchess."user".password AS reactchess_user_password, reactchess."user".create_date AS reactchess_user_create_date, reactchess."user".update_date AS reactchess_user_update_date 
FROM reactchess."user" 
WHERE reactchess."user".email = %(email_1)s 
 LIMIT %(param_1)s
2021-10-14 14:28:12,090 - INFO - [cached since 33.51s ago] {'email_1': 'duynguyenngoc@hotmail.com', 'param_1': 1}
2021-10-14 14:28:12,365 - INFO - ROLLBACK
2021-10-14 14:28:26,535 - INFO - BEGIN (implicit)
2021-10-14 14:28:26,537 - INFO - SELECT reactchess."user".id AS reactchess_user_id, reactchess."user".first_name AS reactchess_user_first_name, reactchess."user".last_name AS reactchess_user_last_name, reactchess."user".email AS reactchess_user_email, reactchess."user".phone AS reactchess_user_phone, reactchess."user".password AS reactchess_user_password, reactchess."user".create_date AS reactchess_user_create_date, reactchess."user".update_date AS reactchess_user_update_date 
FROM reactchess."user" 
WHERE reactchess."user".email = %(email_1)s 
 LIMIT %(param_1)s
2021-10-14 14:28:26,538 - INFO - [cached since 47.96s ago] {'email_1': 'duynguyenngoc@hotmail.com', 'param_1': 1}
2021-10-14 14:28:26,820 - INFO - ROLLBACK
2021-10-14 14:30:31,424 - INFO - Shutting down
2021-10-14 14:30:31,526 - INFO - Waiting for connections to close. (CTRL+C to force quit)
2021-10-14 14:30:34,013 - INFO - BEGIN (implicit)
2021-10-14 14:30:34,015 - INFO - SELECT reactchess."user".id AS reactchess_user_id, reactchess."user".first_name AS reactchess_user_first_name, reactchess."user".last_name AS reactchess_user_last_name, reactchess."user".email AS reactchess_user_email, reactchess."user".phone AS reactchess_user_phone, reactchess."user".password AS reactchess_user_password, reactchess."user".create_date AS reactchess_user_create_date, reactchess."user".update_date AS reactchess_user_update_date 
FROM reactchess."user" 
WHERE reactchess."user".email = %(email_1)s 
 LIMIT %(param_1)s
2021-10-14 14:30:34,017 - INFO - [cached since 175.4s ago] {'email_1': 'duynguyenngoc@hotmail.com', 'param_1': 1}
2021-10-14 14:30:34,308 - INFO - ROLLBACK
2021-10-14 14:30:34,338 - INFO - Waiting for application shutdown.
2021-10-14 14:30:34,339 - INFO - Application shutdown complete.
2021-10-14 14:30:34,340 - INFO - Finished server process [317]
2021-10-14 14:30:36,830 - INFO - Started server process [421]
2021-10-14 14:30:36,831 - INFO - Waiting for application startup.
2021-10-14 14:30:36,832 - INFO - Application startup complete.
2021-10-14 14:30:38,879 - INFO - select pg_catalog.version()
2021-10-14 14:30:38,879 - INFO - [raw sql] {}
2021-10-14 14:30:38,883 - INFO - select current_schema()
2021-10-14 14:30:38,884 - INFO - [raw sql] {}
2021-10-14 14:30:38,887 - INFO - show standard_conforming_strings
2021-10-14 14:30:38,887 - INFO - [raw sql] {}
2021-10-14 14:30:38,889 - INFO - BEGIN (implicit)
2021-10-14 14:30:38,894 - INFO - SELECT reactchess."user".id AS reactchess_user_id, reactchess."user".first_name AS reactchess_user_first_name, reactchess."user".last_name AS reactchess_user_last_name, reactchess."user".email AS reactchess_user_email, reactchess."user".phone AS reactchess_user_phone, reactchess."user".password AS reactchess_user_password, reactchess."user".create_date AS reactchess_user_create_date, reactchess."user".update_date AS reactchess_user_update_date 
FROM reactchess."user" 
WHERE reactchess."user".email = %(email_1)s 
 LIMIT %(param_1)s
2021-10-14 14:30:38,895 - INFO - [generated in 0.00112s] {'email_1': 'duynguyenngoc@hotmail.com', 'param_1': 1}
2021-10-14 14:30:39,324 - INFO - ROLLBACK
2021-10-14 14:32:17,148 - INFO - BEGIN (implicit)
2021-10-14 14:32:17,150 - INFO - SELECT reactchess."user".id AS reactchess_user_id, reactchess."user".first_name AS reactchess_user_first_name, reactchess."user".last_name AS reactchess_user_last_name, reactchess."user".email AS reactchess_user_email, reactchess."user".phone AS reactchess_user_phone, reactchess."user".password AS reactchess_user_password, reactchess."user".create_date AS reactchess_user_create_date, reactchess."user".update_date AS reactchess_user_update_date 
FROM reactchess."user" 
WHERE reactchess."user".email = %(email_1)s 
 LIMIT %(param_1)s
2021-10-14 14:32:17,151 - INFO - [cached since 98.26s ago] {'email_1': 'duynguyenngoc@hotmail.com', 'param_1': 1}
2021-10-14 14:32:17,454 - INFO - ROLLBACK
2021-10-14 14:39:38,013 - INFO - BEGIN (implicit)
2021-10-14 14:39:38,016 - INFO - SELECT reactchess."user".id AS reactchess_user_id, reactchess."user".first_name AS reactchess_user_first_name, reactchess."user".last_name AS reactchess_user_last_name, reactchess."user".email AS reactchess_user_email, reactchess."user".phone AS reactchess_user_phone, reactchess."user".password AS reactchess_user_password, reactchess."user".create_date AS reactchess_user_create_date, reactchess."user".update_date AS reactchess_user_update_date 
FROM reactchess."user" 
WHERE reactchess."user".email = %(email_1)s 
 LIMIT %(param_1)s
2021-10-14 14:39:38,017 - INFO - [cached since 539.1s ago] {'email_1': 'duynguyenngoc@hotmail.com', 'param_1': 1}
2021-10-14 14:39:38,350 - INFO - ROLLBACK
2021-10-14 14:47:21,631 - INFO - Shutting down
2021-10-14 14:47:21,745 - INFO - Waiting for application shutdown.
2021-10-14 14:47:21,757 - INFO - Application shutdown complete.
2021-10-14 14:47:21,803 - INFO - Finished server process [421]
